### ISSUE TITLE
Recheck encoding of i18n files

### ISSUE THREAD

**Issue by lukasriederle** [SAP/ui5-tooling#161]
## Expected Behavior
i18n files should be readable in UTF8 at least as option
## Current Behavior
utf8 files get read with wrong character set what leads to issues with e.g. German umlauts
Especially this is an issue in combination with SAP Translation Hub witch is translating into UTF8
using a manual conversion is not an option for bigger projects with many languages.
https://github.com/SAP/ui5-builder/issues/105

## Steps to reproduce the issue
see https://github.com/SAP/ui5-builder/issues/105

## Context
see https://github.com/SAP/ui5-builder/issues/105

## Affected components *(if known)*

- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [x] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
see https://github.com/SAP/ui5-builder/issues/105

**Comment by htammen** [comment]
I opened a similar issue in ui5-server. This was fixed with ui5-cli version 1.5.3. 
Probably this is helpful for you, too.

**Comment by matz3** [comment]
We are currently working on a concept to better handle encoding of properties files: https://github.com/SAP/ui5-tooling/pull/168

**Comment by RandomByte** [comment]
With UI5 CLI [`v1.7.0`](https://github.com/SAP/ui5-cli/releases/tag/v1.7.0), you can now configure `UTF-8` as the source encoding of a projects `*.properties` files. The default stays at `ISO-8859-1`. In both cases the UI5 Tooling will escape any non-ASCII characters, so that the build result is independent from the encoding.

📖 [Documentation](https://sap.github.io/ui5-tooling/pages/Configuration/#resources-optional) (see `propertiesFileSourceEncoding`)  
🔎 [Demo](https://github.com/SAP/openui5-sample-app/pull/54)
