### ISSUE TITLE
ui5-server: Add timeout property to settings

### ISSUE THREAD

**Issue by iljapostnovs** [SAP/ui5-tooling#471]
## Is your feature request related to a problem? Please describe.
"express" server has default timeout value set to 2 min, which means that all requests, which takes more than 2 min to process, fails.

## Describe the solution you'd like
Please add another property in ui5-server settings: timeout.

## Additional context
This place helped me to solve the issue:
@ui5->server->lib->server.js
![image](https://user-images.githubusercontent.com/31005247/102218876-59ce6c80-3ee7-11eb-8ad5-73c1f0796e71.png)

**Comment by RandomByte** [comment]
Hi @iljapostnovs!

Sounds reasonable. I did some digging and found that this timeout is actually defined by the Node.js server: https://nodejs.org/dist/latest-v12.x/docs/api/http.html#http_server_settimeout_msecs_callback

And since Node.js v13.0.0 the default timeout is actually removed: https://github.com/nodejs/node/pull/27558 (also see the [latest documentation](https://nodejs.org/dist/latest/docs/api/http.html#http_server_settimeout_msecs_callback)).

Which version of Node.js are you using?

Also, are using the `@ui5/cli` or the `@ui5/server` Node.js API?

**Comment by iljapostnovs** [comment]
Hi @RandomByte,
Indeed, I had Node.js v12.18. I've updated it and now there is no issue with timeout.
I am using @ui5/cli.

Maybe this enhancement doesn't make sence anymore, but thanks for your answer :)

**Comment by RandomByte** [comment]
If you are fine with using a newer Node.js version for your scenario, then I would say we close this issue for the time being. If someone comes up with this requirement for any older versions we can still re-open it.
