### ISSUE TITLE
Feature Request: generic test-resources avail. via UI5-Tooling libraries

### ISSUE THREAD

**Issue by stesap** [SAP/ui5-tooling#488]
## Is your feature request related to a problem? Please describe.
When writing tests for Fiori-Elements flooplans, I want to reuse code from assertion classes of the following files
- `test-resources/sap/suite/ui/generic/template/integration/testLibrary/ListReport/pages/assertions/ListReportAssertions.js`
- `test-resources/sap/suite/ui/generic/template/integration/testLibrary/ObjectPage/pages/assertions/ObjectPageAssertions.js`

When I use Karma-UI5 and want to leverage the UI5-Tooling for serving needed modules, the test-resources for generic controls aren't available. 

**ui5-local.yaml**
```yaml
  libraries:
    - name: sap.f
    - name: sap.m
    - name: sap.suite.ui.generic.template
```

As I've seen in this comment (https://github.com/SAP/ui5-tooling/issues/256#issuecomment-681965908), the avail. test-resources via the libraries can be configured.

## Describe alternatives you've considered
Currently, I've configured in karma config `url` property with the <https://ui5.sap.com>, to get resources and test-resources. But then I cannot make use of the customMiddlewares which are already defined in `ui5.yaml`.

**Comment by RandomByte** [comment]
Hi and thanks for reporting this feature requests.

Ultimately this will be a decision for the sap.suite.ui.generic.template library owners to make. Our opinion (UI5 Core) is that test-resources should ideally only contain the tests for the library itself. This means a library's test-resources should not be required from outside the library. Resources like the ones you mentioned should rather be part of the library's "resources" or of an additional "sap.suite.ui.generic.template testing" library.

However, this is not always the case for today's UI5 libraries. And they typically have rather good reasons for that.

Anyways, this is not something we can fix in the UI5 Tooling project. Since the library in question is an SAPUI5 library, I would kindly ask you to raise an SAP support incident so that the responsible team can take a look into it and work out a good solution.
