### ISSUE TITLE
Documentation of Dependency management or a flag to rely on npm

### ISSUE THREAD

**Issue by bkrrrr** [SAP/ui5-tooling#521]
We use for our software gitlab with a very traditional pipeline. install -> build -> test -> deploy.

**Feature Request** 
- enable ui5 tooling to use only ui5 version and dependencies as declared in package.json. E.g. switch off the tooling dependency management, therefore aboard with an error if something is missing. 
- if this is not an option document what is installed from where, how a proxy can be provided(ci servers are behind a vpn) and how this can be cached and/or preinstalled e.g. a ```ui5 install```would be handy. 

Why? 
 - there are plenty of tools to check, update and manage npm dependencies but basically none for ui5-tooling.
 - Caches for npm dependencies are updated/create and scanned for malicious code during install. All up to date pipelines do this out of the box for npm. Installing something on the side is strange
 - IMHO: npm 7 comes with workspaces; ui5-tooling dependency management should also be able to work with them. Maybe another good reasons to give developer the option to use what npm offers out of the box.
 
 
 **Further Details**

Package.json snipped
```json
"devDependencies": {
        "@openui5/sap.f": "^1.89.1",
        "@openui5/sap.m": "^1.89.1",
        "@openui5/sap.tnt": "^1.89.1",
        "@openui5/sap.ui.codeeditor": "^1.89.1",
        "@openui5/sap.ui.core": "^1.89.1",
        "@openui5/sap.ui.fl": "^1.89.1",
        "@openui5/sap.ui.layout": "^1.89.1",
        "@openui5/sap.ui.support": "^1.89.1",
        "@openui5/sap.ui.testrecorder": "^1.89.1",
        "@openui5/sap.ui.unified": "^1.89.1",
        "@openui5/themelib_sap_fiori_3": "^1.89.1",
        "@ui5/cli": "2.10.3",
        "@wdio/cli": "~7.5.2",
        "@wdio/junit-reporter": "~7.5.2",
        "@wdio/local-runner": "~7.5.2",
        "@wdio/spec-reporter": "~7.5.2",
        "ui5-middleware-livereload": "~0.5.3",
        "ui5-middleware-simpleproxy": "~0.7.1"
    },
    "ui5": {
        "dependencies": [
            "ui5-middleware-simpleproxy",
            "ui5-middleware-livereload",
            "@openui5/sap.f",
            "@openui5/sap.m",
            "@openui5/sap.tnt",
            "@openui5/sap.ui.codeeditor",
            "@openui5/sap.ui.core",
            "@openui5/sap.ui.fl",
            "@openui5/sap.ui.layout",
            "@openui5/sap.ui.support",
            "@openui5/sap.ui.testrecorder",
            "@openui5/sap.ui.unified",
            "@openui5/themelib_sap_fiori_3"
        ]
    },
```

Log:
![image](https://user-images.githubusercontent.com/14314310/118133124-be431880-b400-11eb-8809-8ec67773aa86.png)

Ui5-tooling creates this logs(omitting declaration in ui5 changes the message a bit) and i cant figure out how to switch off/resolve the dep-management by ui5-tooling. In our case "self-containing-build" there should be a simple switch so, that ui5 tooling is using the provided npm dev dependencies instead of what happend right now.

**Comment by RandomByte** [comment]
I think I'll need some more information to better understand your request.

> enable ui5 tooling to use only ui5 version and dependencies as declared in package.json. E.g. switch off the tooling dependency management, therefore aboard with an error if something is missing.

By default, UI5 Tooling resolves your project's dependencies based on the package.json. We use the standard Node.js module resolution, so npm v7 workspaces should work just like Yarn's PnP does.

What seems to happen in your case is that in addition to the OpenUI5 dependencies in your package.json, you also seem to have declared framework dependencies in the ui5.yaml as documented here: https://sap.github.io/ui5-tooling/pages/OpenUI5/#configuration

You should only declare one or the other. Now the ui5.yaml framework dependencies take precedence over the OpenUI5 dependencies in your package.json. Since we recommend the ui5.yaml configuration, you get log messages stating that the package.json dependencies should be removed.

However, if you would like to stick with the package.json dependencies that's totally fine too. Just remove the framework configuration from your project's ui5.yaml.

> if this is not an option document what is installed from where, how a proxy can be provided(ci servers are behind a vpn)

If you decide to stick with the ui5.yaml configuration, you can control proxy and registry settings the same way as for the npm CLI. We use [libnpmconfig](https://github.com/npm/libnpmconfig) internally. So we respect any .npmrc file. AFAIK only global npm configuration is not read. I think proxy configuration is done via environment variables HTTP_PROXY and HTTPS_PROXY and should be respected by us.

> and how this can be cached and/or preinstalled e.g. a `ui5 install` would be handy.

Since UI5 Tooling installs dependencies transparently, on-demand, we decided against such an explicit command. For CI setups, we recommend sharing/caching the `~/.ui5/framework/` directory across jobs. The first job to use a new UI5 version will then fetch all packages once and cache them for all other jobs.

However, `ui5 tree --full` should be a good workaround for your request. It fetches and caches any missing packages, writes out the configured dependency tree and finishes.

> Caches for npm dependencies are updated/create and scanned for malicious code during install. All up to date pipelines do this out of the box for npm. Installing something on the side is strange

AFAIK npm only scans package dependencies for reported vulnerabilities. Since UI5 framework packages don't declare any thirdparty dependencies I don't see any drawback from not having this audit step. All packages installed by UI5 Tooling are published by us (=UI5 Framework). I guess we could add the audit API to our installer in the future if it becomes more powerful and relevant for frontend packages.

For more background information on why we chose to manage UI5 framework dependencies ourselves, please also see this blog post: https://blogs.sap.com/2020/04/01/ui5ers-buzz-49-the-ui5-tooling-and-sapui5-the-next-step/

I hope this helps understanding our framework installer mechanism. Please let us know if I missed an aspect of your request or if you face other issues or missing features. Thanks!

**Comment by bkrrrr** [comment]
thanks, 

i was totally missing that the framework declaration in ui5.yaml is optional in my case.
and i was looking for ```~/.ui5/framework/```.

This explanation is great, should be part of the documentation
