### ISSUE TITLE
add additional files to zipper

### ISSUE THREAD

**Issue by zkhezane** [SAP/ui5-tooling#524]
## Expected Behavior

Hello we need to copy 2 files form a node_modules that exists in the parent folder, to a folder lib in the webappp folder.
we used to do that like this 
```javascript


 luxon: {
            expand: true,
            src: '*min.js',
            cwd: 'node_modules/luxon/build/global/',
            dest: 'webapp/libs/'
        },
  moment: {
            expand: true,
            src: '*moment.min.js',
            cwd: 'node_modules/moment/min',
            dest: 'webapp/libs/'
        },

```

## Current Behavior
Actually, we're able to add those 2 files in the workplace, but the  zipper task doesn't find them in the resources, so they are not added to the zip file.

## Steps to Reproduce the Issue

link to the ui5 yaml file : <Removed internal URL (RandomByte)>
1. git clone project,
2. run npm run ui5 in ui-run-mapping folder

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by zkhezane** [comment]
Is there anyway I can create this issue in internal github ?

**Comment by tobiasso85** [comment]
Hi @zkhezane,

the UI5 Tooling does not offer a task called `zipper` and I need more information to reproduce the issue,
such as the content of your ui5.yaml, the version of the UI5 Tooling used, the expected behaviour and the actual behaviour.

Please refer to:
[Reporting Issues](https://github.com/SAP/ui5-tooling/blob/master/CONTRIBUTING.md#-reporting-issues)

This is the official repository for the UI5 Tooling.

Regards
Tobias

**Comment by vobu** [comment]
even though I'm external (aka non-SAP :) ) and don't want to interfere here, I have the hunch that the req for copying `luxon`/`moment` stems from the much common scenario of date manipulation in the built app. 
but instead of copypasta these files in CD, the much more elegant and native-to-`ui5-tooling` solution is to simply include the 2 node modules via `ui5.yaml`: https://blogs.sap.com/2020/07/30/project-shims-using-npm-modules-with-ui5/
then, `ui5 build` will recognize these `luxon` and `moment` at build time and put them in your `dist` build.

**Comment by zkhezane** [comment]
thanks @vobu 
This is exactly what we're looking for.
