### ISSUE TITLE
Can you use UI5 Tooling for doing the SAPUI5 Walkthrough

### ISSUE THREAD

**Issue by stefania-santimbrean** [SAP/ui5-tooling#530]
Hello,

For someone new to UI5 who wants to start learning and maybe start with the [Walkthrough](https://sapui5.hana.ondemand.com/#/topic/3da5f4be63264db99f2e5b04c5e853db) is it possible to use UI5 Tooling and VSCode?

I downloaded for example the [code for Step 8](https://sapui5.hana.ondemand.com/#/entity/sap.m.tutorial.walkthrough/sample/sap.m.tutorial.walkthrough.08) and tried `npm install` and then `npm start` which is doing `ui5 serve`, but I get the following error:
```
Error Message:
Could not find required manifest.json for project sap.m.tutorial.walkthrough.08: ENOENT: no such file or directory,
```

I was expecting this to not be a problem in Step 10 where there is a manifest.json but it throws the same error:
![image](https://user-images.githubusercontent.com/74544010/124141508-25d92400-da92-11eb-8d7d-b3367ba9549e.png)

Is it something wrong in the configuration or not possible?

Kind regards,
Stefania

**Comment by svbender** [comment]
Hi,

Thanks for reporting this issue. The samples are not correct in this case.
This is not an issue with the ui5-tooling, therefore I have created an issue on openui5: https://github.com/SAP/openui5/issues/3292


If you want to proceed with the tutorial, try the following steps to fix it:

1. The ui5-tooling requires a `manifest.json` file which is only introduced since step 10 of the walkthrough. Before this step you can add a `manifest.json` with the minimum requirements in the webapp folder:
```json
{
  "sap.app":{
    "id":"sap.ui.demo.walkthrough",
    "type":"application"
  }
}
```

2. The path to the webapp is wrong and needs to be changed in the `ui5.yaml`:
```
webapp:"./webapp/"
```
This webapp path is the default one which means you can also remove the `resources: configuration: paths: ...` part.

3. The dependencies in the `package.json` aren't complete. The `sap.m` and `sap.ui.core` dependencies are missing. Add `sap.m` and `sap.ui.core` as shown below and run `npm install` again or directly install them:
```json
"dependencies":{
"@openui5/sap.m":"^1",
"@openui5/sap.ui.core":"^1",
"@openui5/themelib_sap_fiori_3":"^1"
},
```

Best regards,
Sven
