### ISSUE TITLE
SpreadsheetWorker.js not served from sap-ui-custom.js

### ISSUE THREAD

**Issue by faow** [SAP/ui5-tooling#538]
## Expected Behavior
Self-contained builds are standalone and dont rely on files served from CDN or SAP-System-Version.
`SpreadsheetWorker.js` is served from `sap-ui-custom.js` for self-contained builds.

## Current Behavior
`SpreadsheetWorker.js` is served from `..resources/sap...` which is the SAP-System-Version of the file and also requires some additional files from the same location. This leads to errors, because the System-Version is not up-to-date.
![image](https://user-images.githubusercontent.com/75840472/126319744-0d82d019-29bb-4892-bd99-faf2aa2695e4.png)

Is there any way to include these files in the bundle?
I tried it with a custom bundle and a self-contained build with a standard application.

## Steps to Reproduce the Issue
SampleApp: https://github.com/DSC-GMBH/sap.ui.comp.sample.smarttable 
1. Use `npm run buildbasic` to build a self-contained build
2. Use `npm run startdist` to serve the dist files
3. Watch the console on clicking the download button

Alternative way:
1. Use `npm run build` to build a custom bundle build 
2. Use `npm run startdist` to serve the dist files
3. Watch the console on clicking the download button
There is also additional Information available:
![image](https://user-images.githubusercontent.com/75840472/126321322-06a41c32-2b2c-4665-829f-b3eaaa900ce6.png)

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): `2.11.3`
 * Node.js Version: `14.17.0`
 * npm Version: `7.9.0`
 * OS/Platform: `Windows`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace
```
WARN lbt:bundle:Builder **** warning: module sap/ui/export/js/SpreadsheetWorker.js requires top level scope and can only be embedded as a string (requires 'eval')
verb lbt:bundle:Builder     sap/ui/export/js/SpreadsheetWorker.js (1670,1070)
```

**Comment by matz3** [comment]
The `sap/ui/export/js/SpreadsheetWorker.js` seems to be loaded within a Web Worker while the `sap-ui-custom.js` bundle is loaded in the main thread.
Furthermore the bundles created by the UI5 Tooling and the ui5loader in general are currently only supported within the main thread, not within a Web Worker or Service Worker. Sharing code between them would anyways be not straightforward.

To prevent issues with version differences I'd like to suggest that you use the `--all` flag to also build the dependencies (like sap.ui.export) in order to make those files available within the `dist` folder.

As the whole worker topic is currently not on our roadmap, I'm closing this issue.
