### ISSUE TITLE
Timeout in Jenkins pipeline

### ISSUE THREAD

**Issue by melwinlobo18** [SAP/ui5-tooling#549]
We're using the ui5-tooling in our project at SAP. It works great when we're developing the application locally. But when the build runs in the Jenkins pipeline, a timeout occurs as our Jenkins pipeline doesn't have access to the public NPM repository. How can we resolve this?

**Comment by matz3** [comment]
Are you referring to the `npm install`, which can't be executed, or the download of UI5 libraries via the `framework` configuration? (see https://sap.github.io/ui5-tooling/pages/OpenUI5/ / https://sap.github.io/ui5-tooling/pages/SAPUI5/)

Our UI5 framework functionality is supposed to use the same configuration as npm does, so it should behave the same as `npm install`. If it doesn't, we should definitely look into this from UI5 Tooling side.

Otherwise I'd categorize this as an issue not specific to this project but to a npm/yarn project setup in general, thus we can't really provide support for it.
