### ISSUE TITLE
ui5 builder fails to recognize custom task

### ISSUE THREAD

**Issue by vobu** [SAP/ui5-tooling#567]
## Expected Behavior
`ui5 build` recognizes a custom task in `ui5.yaml` and executes it

## Current Behavior
`ui5 build` fails with 
```bash
Error Message:
taskRepository: Unknown Task $task
```

## Steps to Reproduce the Issue
this happened after bumping  `ui5/cli` from 2.12.0 to 2.12.1 in a PR in the ecosys showcase: https://github.com/ui5-community/ui5-ecosystem-showcase/pull/541
1. checkout PR
2. modify `packages/ui5-app/package.json` to use `@ui5/cli` 2.12.1
2. run `yarn workspace ui5-task-zipper test`
3. observe above error message

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.12.1`**
 * Node.js Version: **`v14.17.6`**
 * npm Version: `v6.14.15`
 * OS/Platform: `macOS 11.6`
 * Browser *(if relevant)*: ---
 * Other information regarding your environment *(optional)*: ---

## Log Output / Stack Trace
see the attached files with the names according to ui5 version cli
[ui5.cli.2.12.0.log](https://github.com/SAP/ui5-tooling/files/7245906/ui5.cli.2.12.0.log)
[ui5.cli.2.12.1.log](https://github.com/SAP/ui5-tooling/files/7245908/ui5.cli.2.12.1.log)

**Comment by RandomByte** [comment]
Pretty sure this is caused by https://github.com/SAP/ui5-tooling/issues/302

This is a common issue with Yarn since it doesn't honor the `npm-shrinkwrap.json` of the CLI. Please update your lockfile to make sure that there is only a single `@ui5/builder` installation. The easiest way to achieve this is to remove `node_modules/` and `yarn.lock` and installing the dependencies again.

**Comment by vobu** [comment]
FTR: can confirm that it was a yarn issue
&rarr; `rm yarn.lock`, then updating to `ui5/cli 2.12.1`, then `yarn install` enabled the tests to work
