### ISSUE TITLE
xml view property binding using types does not require classes (self contained build)

### ISSUE THREAD

**Issue by hschaefer123** [SAP/ui5-tooling#57]
## Expected Behavior
Using xml view with bound type should include dependencies inside self-contained build dow not detect 
declared types.

## Current Behavior
used classed will be lazy loaded 

## Steps to reproduce the issue
<Text text="{ parts:[{path:'unitNetAmount'},{path:'currency'}], type: 'sap.ui.model.type.Currency', formatOptions: {showMeasure: false} }"/>

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)

**Comment by codeworrior** [comment]
While I understand this requirement in general, it is not as straightforward as it might look.

IMO, an important cornerstone for the build tooling is that it should be consistent with the runtime code. and the binding parser at runtime DOES NOT REQUIRE any type by name. It looks a given type or formatter up by its global name, but it does not load it. It is therefore a requirement for apps already today that they require any uncommon types that they use in XMLViews.

The fact that this looks different for your is caused by the lazy stubs that the sap.ui.core library creates for all built-in types. When they are accessed by their global name, the corresponding module is loaded synchronously behind the scenes.

I can imagine that the tooling either uses a type or static formatter name to probe for a corresponding module. If it is found, it would be added. But this won't cover all cases. If a single module defines 5 custom types, those would not be found by their name.

Alternatively, the tooling could know about the lazy stubs and the names that they stub. It would add the corresponding modules only for those names.

To be discussed.

**Comment by hschaefer123** [comment]
Hi Frank,

from my point of view, the xmlviewer parser inside tooling should be able to handle this. 

Currently we are not forced to use a view with a controller. The negative impact would be, that we have to push all such view requirements into the component.js requirement. This seems to be quite ugly!

Another approach would be, to have a declarative requirements section inside the view.

With introducing the new event handler parameter syntax maybe directly calling a 
```
press="sap.m.MessageBox.show('Hello')"
```
this needs to be handled the same way or we will have very long component.js files.

To be continued...

**Comment by boghyon** [comment]
https://github.com/SAP/openui5/issues/2475 (Related feature request)

**Comment by matz3** [comment]
The referenced OpenUI5 has been solved by introducing a `core:require` mechanism for XMLViews with v1.69.0. See https://github.com/SAP/openui5/issues/2475#issuecomment-521648399 for details. This also supports model types.

UI5 Builder support will be enabled via https://github.com/SAP/ui5-builder/pull/304.
