### ISSUE TITLE
Themelib path error for less files while building the repo

### ISSUE THREAD

**Issue by YogitaGurnani** [SAP/ui5-tooling#615]
## Expected Behavior
Attached is a zipped-up project to make it fast to see this issue. This project extends the Belize and Fiori_3 theme and needs to reference the theme from the node_modules.

## Current Behavior
The problem is we have imported the belize, fiori_3 and @openui5/sap.ui.core from the npm, and these all creating the folder structure from resources, while trying to build the project whatever is the latest node_module structure it is referring that and trying to match other themes in that folder, which is giving an error.

## Steps to Reproduce the Issue

1. Access the project from here (https://sap-my.sharepoint.com/:u:/p/yogita_gurnani/EX9uhn0HWONAnHNdbB-v-XgBVH2Cll7f9DUH_Bz1YOBRmw?e=mc8cst )
2. cd into the unzipped project
3. npm install
4. npm run build

## Context
All the versions are mentioned in the package.json

## Log Output / Stack Trace
info builder:builder Building project iotainlibreusable not including dependencies...
info builder:builder �   (1/1) Building project iotainlibreusable
info builder:builder library iotainlibreusable � (1/14) Running task escapeNonAsciiCharacters...
info builder:builder library iotainlibreusable � (2/14) Running task replaceCopyright...
info builder:builder library iotainlibreusable � (3/14) Running task replaceVersion...
info builder:builder library iotainlibreusable � (4/14) Running task replaceBuildtime...
info builder:builder library iotainlibreusable � (5/14) Running task generateLibraryManifest...
info builder:builder library iotainlibreusable � (6/14) Running task webide-extension-task-updateManifestJson...
devxUpdateManifest - datasource.uri attribute in the manifest.json file was not found or incorrect. Therefore, update this attribute to be reletive uri is irrelevant.
info builder:builder library iotainlibreusable � (7/14) Running task generateManifestBundle...
WARN builder:processors:bundlers:manifestBundler Could not find any resources for i18n bundle '/resources/sap/iot/ain/lib/reusable'
info builder:builder library iotainlibreusable � (8/14) Running task generateLibraryPreload...
info builder:builder library iotainlibreusable � (9/14) Running task buildThemes...
File not found: /resources/sap/sap/ui/core/themes/sap_bluecrystal/base.less(9/14) Running task buildThemes...
File not found: /resources/sap/sap/ui/core/themes/sap_bluecrystal/global.less
File not found: /resources/sap/ui/core/themes/base/base.less
File not found: /resources/sap/ui/core/themes/base/global.less
ERR! builder:processors:themeBuilder Error while compiling /resources/sap/iot/ain/lib/reusable/themes/sap_bluecrystal/library.source.less: Could not find file at path '/resources/sap/sap/
ui/core/themes/sap_bluecrystal/base.less'
ERR! builder:builder Build failed in 1.53 s
info builder:builder Executing cleanup tasks...

⚠️  Process Failed With Error

Error Message:
Could not find file at path '/resources/sap/sap/ui/core/themes/sap_bluecrystal/base.less'

For details, execute the same command again with an additional '--verbose' parameter
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! iotainlibreusable@0.0.1 build: `ui5 build --include-task=generateManifestBundle generateCachebusterInfo`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the iotainlibreusable@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\I329082\AppData\Roaming\npm-cache\_logs\2022-04-26T09_22_00_968Z-debug.log

**Comment by matz3** [comment]
The project uses openui5 dependencies within the `package.json` file, but defines a "ui5 dependencies" array with just the `@sap/ui5-builder-webide-extension`. The list needs to include all relevant packages from "dependencies" / "devDependencies" so that they are taken into account.

But in general, we don't recommend to define framework library dependencies in the package.json anymore.
Please have a look into [Consuming OpenUI5 Libraries](https://sap.github.io/ui5-tooling/pages/OpenUI5/) / [Consuming SAPUI5 Libraries](https://sap.github.io/ui5-tooling/pages/SAPUI5/) to see how you can add framework dependencies to the ui5.yaml instead.

Apart from that, I would discourage using less variables for import paths (e.g. `@path : "../../../../../../sap/ui/core/themes/sap_belize_hcw";`) as this seems to cause some issues in path resolution. Please rather add static relative paths like in the OpenUI5 libraries (e.g. [sap.m](https://github.com/SAP/openui5/blob/master/src/themelib_sap_belize/src/sap/m/themes/sap_belize_plus/library.source.less)).
