### ISSUE TITLE
[Feature Request]: Add cli support for adding/removing ui5 dependencies to/from the package.json

### ISSUE THREAD

**Issue by zdravko-georgiev** [SAP/ui5-tooling#631]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
If I want to use a custom middleware with `ui5-tooling`, then I need to add i to `devDependencies` and to`ui5 dependencies` in the `package.json`, e.g.
```JSON
"devDependencies": {
    "my-custom-middleware": "1",
},
"ui5": {
    "dependencies": [
        "my-custom-middleware"
    ]
}
```
Adding to `devDependencies` is done automatically by executing `npm i my-custom-middleware`, but the entry to `ui5 dependencies` needs to be done manually. It would be nice if this can be done also programmatically. E.g.
**Adding**
```
ui5 add --pkg my-custom-middleware
```

**Removing**
```
ui5 remove --pkg my-custom-middleware
```

**Comment by cfg74** [comment]
+1

**Comment by RandomByte** [comment]
Hey Zdravko, thanks for reporting. We would rather like to get rid of this workaround.

UI5 Tooling 3.0, currently available as alpha release (see https://sap.github.io/ui5-tooling/updates/migrate-v3/), will be able to reliably detect relevant modules in `dependencies` and `devDependencies` without the additional `ui5` configuration. Also see https://github.com/SAP/ui5-project/pull/457

Leaving this open since UI5 Tooling 3.0 is still in development and we can't provide n ETA for its release yet.

**Comment by zdravko-georgiev** [comment]
Hi Merlin,
thanks for the info, I will check the links that you provided.

**Comment by flovogt** [comment]
As UI5 Tooling 3.0 is released, closing this. With UI5 Tooling 3.0 it is no longer necessary to specify the devDependencies also in the `ui5/dependencies` section in the `package.json`
