### ISSUE TITLE
devDependencies are treated transitively as "dependencies" on consuming package

### ISSUE THREAD

**Issue by nlunets** [SAP/ui5-tooling#655]
I'm not entirely sure this falls into bug report or feature request but we have an issue when consuming package built using the ui5 tooling.

The package A declares devDependencies to build time dependencies for transpilation or other things which are only relevant for the development of that package and not the consumption (a.k.a devDependencies), they are still defined in the ui5 section of the package.json because we need them for the build and serve time.

However when package B depends on package A the npm translator now except those dependencies to be available which doesn't make sense.

## Expected Behavior

Package B should ignore ui5 dependencies that were devDependencies in the first place

## Current Behavior

Package B asks for them explicitely.

**Comment by RandomByte** [comment]
Hey Nicolas,

this is indeed a gap in the design of the npm translator. The "ui5" configuration in the package.json was implemented as an undocumented workaround to reduce the number of dependencies the translator will analyze (see also https://github.com/SAP/ui5-tooling/issues/311#issuecomment-779401749).

If you remove the ui5 section, the translator should work as expected: Transitive devDependencies are ignored, they are only analyzed for the current root project.

The upcoming UI5 Tooling v3 should resolve this by making dependency analysis more efficient and hence making the workaround superfluous. It should then always work in the expected way.

If you have a few minutes you could already give the current v3 alpha release a try: https://sap.github.io/ui5-tooling/updates/migrate-v3/. Note that this version always ignores the ui5 section in the package.json

**Comment by RandomByte** [comment]
I beg your pardon, you are right. In UI5 Tooling v2, extensions must be declared as `dependencies`. If declared as `devDependencies`, they must be either listed in the `dependencies` of another project in the dependency tree, or in the  ui5 section of the project's package.json. Otherwise, `devDependencies` are not resolved.

I think the only way to resolve this issue in UI5 Tooling v2 is to move `@sap/ux-ui5-tooling` from `devDependencies` to `dependencies`.

In general, this setup should work fine in the upcoming UI5 Tooling v3 though.

**Comment by matz3** [comment]
Closing this as v3 is released. Please let us know in case there are still issues with that version.
