### ISSUE TITLE
Missing Technical Information Dialog

### ISSUE THREAD

**Issue by kvsrikanthj** [SAP/ui5-tooling#68]
## Expected Behavior
Technical information dialog should open for every UI5 application on keyboard shortcut CTRL + SHIFT + ALT + P

## Current Behavior
Technical information Dialog window doesn't open on keyboard shortcut CTRL + SHIFT + ALT + P

## Steps to reproduce the issue
1. Clone this repository and navigate into it
```
git clone https://github.com/SAP/openui5-sample-app.git
cd openui5-sample-app
```
2. Install all dependencies and start local server
```
npm install
ui5 serve -o index.html
```

## Context
- OS/Platform: Windows 10
- Node.js Version: 8.9.4
- npm Version: 5.6.0

## Affected components
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [X] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Resolution
Always include **sap.ui.layout** library.  Possible solution could be to maintain sap.ui.layout as dependent library for sap.ui.core

**Comment by RandomByte** [comment]
Hi @kvsrikanthj, thanks for reporting! We are aware of this, however this is also the case for various other controls and functionalities. In general the OpenUI5 libraries only define their "essential" dependencies. Without them, the libraries main functionalities do not work.

But for some less popular or uncommon controls or modules you may need to add additional dependencies yourself in order to use them. Also see: https://github.com/SAP/openui5/issues/2150#issuecomment-413317906

Now one could argue that the Technical Information Dialog is somewhat essential. However, for an end-user it is not relevant. Therefore the relevant sap.ui.layout library is not listed as a dependency of the UI5 Core.

Currently we recommend to add sap.ui.layout as a dependency to your project if you would like to use the Technical Information Dialog.

I'm also not really happy with that state. Maybe @codeworrior has a better idea?

**Comment by kvsrikanthj** [comment]
Hi @RandomByte, thanks for the response.
Like you said for end-user it may not be relevant that much. 

Consider this scenario:
Create standalone UI5 app(without npm modules) that refers to OpenUI5 CDN and include sap.m library (either in manifest.json dependencies or index.html bootstrap). Even though sap.ui.layout library is not included we can still open Diagnostics tool, this means there is some kind of internal dependency for sap.m/sap.ui.core and sap.ui.layout

When we consider the above scenario for npm based ui5 modules loading this doesn't work without explicitly adding the dependency sap.ui.layout

**Comment by RandomByte** [comment]
Starting with one of the upcoming OpenUI5 minor releases, sap.m declares a npm dependency to sap.ui.layout.  
Also see https://github.com/SAP/openui5/issues/2150#issuecomment-490503102

This should resolve the reported issue. Therefore closing it for now.

Thanks for reporting!
