### ISSUE TITLE
Should @ui5/fs.AbstractReader be returned if set has size === 0?

### ISSUE THREAD

**Issue by marianfoo** [SAP/ui5-tooling#732]
## Expected Behavior
I expect in a custom Task a @ui5/fs.AbstractReader in `dependencies` when i return in `determineRequiredDependencies` Method a empty set.

## Current Behavior
If i return a empty set in a Task like
````js
module.exports.determineRequiredDependencies = async function({availableDependencies, getProject, getDependencies, options}) {
    return new Set();
}
````
apparently the @ui5/fs.AbstractReader is not returned here but `undefined`:
https://github.com/SAP/ui5-project/blob/145d4a222dfdc796458bbb0f3439d31a8375a71a/lib/build/TaskRunner.js#L433-L436
![image](https://user-images.githubusercontent.com/13335743/209393478-11f35d44-fbc7-4591-a4f4-fa64060d5179.png)
![image](https://user-images.githubusercontent.com/13335743/209393599-ebb9de44-4dbf-49e8-bf3f-c73bae0e9dfb.png)

## Steps to Reproduce the Issue
Return empty set in a custom task.
Task is failing becaue it expects @ui5/fs.AbstractReader and tries to execute `dependencies.byGlob("/**/*.js");`
See https://github.com/ui5-community/ui5-ecosystem-showcase/blob/340ad5607d89101734d3b135b2c20fba79b3db53/packages/ui5-tooling-modules/lib/task.js#L255

## Context
 * UI5 CLI: **`3.0.0-rc.0`**
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`1.108.2`**
 * Node.js Version: **`v18.12.1`**
 * npm Version: `v8.12.1`
 * OS/Platform: `Windows`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
Error Message:
Cannot read properties of undefined (reading 'byGlob')

Stack Trace:
TypeError: Cannot read properties of undefined (reading 'byGlob')
    at module.exports (C:\UI5\ui5-cc-excelUpload\node_modules\ui5-tooling-modules\lib\task.js:256:54)
    at async TaskRunner._executeTask (file:///C:/UI5/ui5-cc-excelUpload/node_modules/@ui5/cli/node_modules/@ui5/project/lib/build/TaskRunner.js:426:3)
    at async TaskRunner.runTasks (file:///C:/UI5/ui5-cc-excelUpload/node_modules/@ui5/cli/node_modules/@ui5/project/lib/build/TaskRunner.js:122:5)
    at async ProjectBuilder.build (file:///C:/UI5/ui5-cc-excelUpload/node_modules/@ui5/cli/node_modules/@ui5/project/lib/build/ProjectBuilder.js:240:6)
    at async ProjectGraph.build (file:///C:/UI5/ui5-cc-excelUpload/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/ProjectGraph.js:572:3)
    at async Object.handleBuild [as handler] (file:///C:/UI5/ui5-cc-excelUpload/node_modules/@ui5/cli/lib/cli/commands/build.js:133:2)
```

**Comment by RandomByte** [comment]
Thanks for checking out the v3 release-candidate!

What you experience works as designed. If a task does not require any dependencies (as indicated by returning empty set in your case), UI5 Tooling will not provide any. We decided to omit the `dependencies` parameter in this case. The alternative would be to provide an "empty" reader, which never returns any resources.

We decided on the first option in order to give tasks the ability to detect whether any dependencies are available. Now they can do so by checking whether the `dependencies` reader has been supplied.

However, we are open for changing this behavior based on community feedback. That's what the RC is for 👍 

Could you elaborate a bit more on the scenario you have there? Im wondering, if the task doesn't require any dependencies, why is the empty `dependencies`-reader problematic? Thanks!

**Comment by marianfoo** [comment]
I think it just needs to be made clear what is being passed there and it can be a undefined `dependencies`. 
Otherwise, I see no problem with the current implementation.
In the linked code sample above the code by Peter Muessig, just does not expect `undefined`.
Unfortunately, I'm not that deep in the code myself, so you'd have to ask Peter about the reasoning.
I just found the "bug" :)

**Comment by RandomByte** [comment]
Alright. But you experienced this error only after implementing the `determineRequiredDependencies` callback?

Just to clarify a few things:

The "ui5-tooling-modules-task" extension should work with UI5 Tooling v3 out of the box. Since it defines [`specVersion 2.2`](https://github.com/ui5-community/ui5-ecosystem-showcase/blob/340ad5607d89101734d3b135b2c20fba79b3db53/packages/ui5-tooling-modules/ui5.yaml#L11), UI5 Tooling will [assume that it requires dependencies](https://sap.github.io/ui5-tooling/v3/pages/extensibility/CustomTasks/#required-dependencies), and provides the reader just like before. It is not necessary to implement the `determineRequiredDependencies` callback.

Only if someone would change the custom task's ui5.yaml to `specVersion: 3.0`, the default is reversed, and no dependencies are provided. Therefore, when upgrading the ui5.yaml to the new Specification Version, the task should also implement the `determineRequiredDependencies` callback and request all available dependencies, like this:

```js
module.exports.determineRequiredDependencies = async function({availableDependencies, getProject, getDependencies, options}) {
    return availableDependencies;
}
```
---

Anyways, I think we should still consider changing the behavior for the `dependencies` parameter from providing `undefined` to an empty reader if no dependencies are requested **_or available_**.

**Comment by marianfoo** [comment]
Thanks for the quick response Merlin.
I have tested it and it works.
Cheers!

**Comment by marianfoo** [comment]
Hi @RandomByte ,
can you tell me approximately when a new @ui5/cli will be released.
The error here is blocking me a bit.
Thanks!

**Comment by matz3** [comment]
@marianfoo [@ui5/cli v3.0.0-rc.1](https://github.com/SAP/ui5-cli/releases/tag/v3.0.0-rc.1) has just been released 🚀

**Comment by marianfoo** [comment]
What a service! :D
Thanks guys, works great!
