### ISSUE TITLE
Building a UI5 project with resourceRoots

### ISSUE THREAD

**Issue by EdStrickland** [SAP/ui5-tooling#789]
Question: Is there a way to config namespace mapping for certain package when building the component preload?

Description: In the application descriptor, I can claime a new namespace for a certain package for other classes to consume. However when UI5-CLI build the application, it seems to be using the appid+relative path to map js files in the component preload, hence the class that is using the package cannot retrieve the source from the preload using this new namespace, a new GET would be called to retrieve the source code causing performance issue.

I understand I may be able to achieve that using nested components but that would cause some refactor effort and may not be my first choice.

**Comment by EdStrickland** [comment]
update: I've successfully exported the classes through a custom UI5 library. I'm trying the project-shims to see if that works.

**Comment by flovogt** [comment]
Hi @edstrickland,
thanks a lot for opening this issue. Some questions from our side:

- Is this error only occurring when migrating from v2 to v3? 
- Which version of the UI5 Tooling do you use?

The defined `resourceRoots` inside a `manifest.json` have to be relative to the namespace of the app/component itself. So pointing to other "external" sources is not intended. In this scenario, you've correctly already described two possible options, go either with project shims or modularize them as nested components depending on your use case.

If you decide for project-shims this project might be interesting for you https://github.com/SAP/openui5-sample-app/blob/use-custom-sinon. If you wanna have a look at nested components this project https://github.com/flovogt/ui5con20-ui5-routing might be helpful.

I'll close this issue here. However feel free to reopen it again. In that case providing a sample would makes the life easier for us to analyze your requirement.
