### ISSUE TITLE
sap-ui-version.json not generated

### ISSUE THREAD

**Issue by T1mey** [SAP/ui5-tooling#825]
Hello SAP,

we have an issue with builing a sapui5 application of type application with the ui5 build command.

For most applications of that type a folder resources with a file "sap-ui-version.json" is generated.
We are relying on the buildTimestamp in that json.

For some applications this folder and the file is not generated.

**Comment by RandomByte** [comment]
It's possible that you upgraded to UI5 Tooling v3 in some of your projects. As noted in the [migration guide](https://sap.github.io/ui5-tooling/stable/updates/migrate-v3/#removal-of-standard-tasks-and-processors), the task `generateVersionInfo` is no longer executed by default.

Try adding the parameter `--include-task generateVersionInfo` to your `ui5 build` command.

**Comment by T1mey** [comment]
Edit found the reason in the migration guide already.
Thanks for your reply.

**Comment by henriquemattos** [comment]
Hi, @RandomByte . I came across this one now, since my self-contained build is expecting to fetch sap-ui-version.json and not finding it. I have reproduced it locally, the file is not generated without explicitly passing `--include-tas generateVersionInfo` . 

Here's the command I'm building the self-contained app:
```sh
ui5 build self-contained --config ui5-dist.yaml --dest webadmin/webapp --clean-dest --all
```

It's not a problem to pass the parameter explicitly, but do you know if this is already known?

Cheers,
Henrique

**Comment by RandomByte** [comment]
> It's not a problem to pass the parameter explicitly, but do you know if this is already known?

Not entirely sure what you mean. As stated in my [comment](https://github.com/UI5/cli/issues/825#issuecomment-1538139255) before, starting with UI5 CLI v3, the task is no longer executed by default. It need to be explicitly included using the parameter. Do you mean something else than this?
