### ISSUE TITLE
getting Error Message: middlewareUtil.getProject is not a function in SAP BAS while previewing sap ui5 APP

### ISSUE THREAD

**Issue by divjail21** [SAP/ui5-tooling#866]
Hi have run command "npm install esendex" in SAP BAS in terminal . after that I am not able to run my UI5 app.

## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by matz3** [comment]
Could you please provide more context information about this error?

Also see #865 where the probable root cause of this error is explained.
However, it would be important to understand where the error happens exactly (in which custom middleware) so that it can be addressed. This is most likely nothing we can fix within UI5 Tooling.

Can you at least provide the contents of your `package.json` and `ui5.yaml` files and which command has been executed within Business Application Studio?

**Comment by flovogt** [comment]
Since there is no response from the author for more than 4 weeks I'm closing the ticket
