### ISSUE TITLE
UI5 Tooling 3.0 internal modules use itself the outdated UI5 Tooling components

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#886]
When installing the latest version of UI5 Tooling 3.0 components, e.g.:

```json
"@sap/ui5-builder-webide-extension": "^1.1.9"
```

and some other (!) UI5 Tooling 3.0 components.

## Expected Behavior
The latest UI5 Tooling 3.0 components will use itself the latest UI5 Tooling 3.0 components.

## Current Behavior
I get:

```
npm WARN deprecated @ui5/logger@1.0.2
npm WARN deprecated @ui5/logger@2.0.1
npm WARN deprecated @ui5/fs@1.1.2
npm WARN deprecated @ui5/fs@2.0.6
UI5 Tooling version 1 and below are out of maintenance.
Migrate your project to the latest version: https://sap.github.io/ui5-tooling/stable/
```

## Steps to Reproduce the Issue
Try to install 

```json
"@sap/ui5-builder-webide-extension": "^1.1.9"
```

And, in generally, check if the UI5 Tooling 3.0 dependencies are completely updated.

## Context
 * Node.js Version: **`20.x`**,  **`21.x`**
 * npm Version: `10.2.0`
 * OS/Platform: `Windows 10 22H2`

## Log Output / Stack Trace

```
npm WARN deprecated @ui5/logger@1.0.2
npm WARN deprecated @ui5/logger@2.0.1
npm WARN deprecated @ui5/fs@1.1.2
npm WARN deprecated @ui5/fs@2.0.6
UI5 Tooling version 1 and below are out of maintenance.
Migrate your project to the latest version: https://sap.github.io/ui5-tooling/stable/
```

**Comment by d3xter666** [comment]
Hi @pubmikeb ,

The latest version of UI5 Tooling is **v3**. We encourage all users to migrate to that version since v1 and v2 are out of maintenance. This could be seen in [v2 documentation page](https://sap.github.io/ui5-tooling/v2/), in NPM: https://www.npmjs.com/package/@ui5/cli/v/2.1.0 as well as in the console, like in your case.

There are migration guidelines in UI5 Tooling's documentation: https://sap.github.io/ui5-tooling/v3/updates/migrate-v3/

You are referencing the package (`@sap/ui5-builder-webide-extension`) from another repository/owner that reuses the UI5 Tooling. Please address your request there.

Best Regards

**Comment by matz3** [comment]
I think there is a bit of a misunderstanding here, and I have to admit, the package names and GitHub repository names can be confusing.

This open-source project (UI5 Tooling) maintains npm packages prefixed with `@ui5/`, such as `@ui5/builder`. The repositories are under the SAP org on GitHub (e.g. https://github.com/SAP/ui5-builder).

The mentioned npm package `@sap/ui5-builder-webide-extension` is provided by a different team at SAP, but not as an open-source project. Unfortunately, the README at https://www.npmjs.com/package/@sap/ui5-builder-webide-extension does not mention how to obtain support. For SAP customers I recommend following the usual support process via https://support.sap.com to address this issue. I have also notified the team about this issue.

**Comment by matz3** [comment]
@pubmikeb you're welcome. Please see my comment in the issue.
