### ISSUE TITLE
Incorrect @ui5/cli release notes

### ISSUE THREAD

**Issue by matz3** [SAP/ui5-tooling#888]
The @ui5/cli releases [v3.4.1](https://github.com/SAP/ui5-cli/releases/tag/v3.4.1) and [v3.5.0](https://github.com/SAP/ui5-cli/releases/tag/v3.5.0) both contain the release notes of [@ui5/project v3.5.1](https://github.com/SAP/ui5-project/releases/tag/v3.5.1).
The notes should only be part of [v3.4.1](https://github.com/SAP/ui5-cli/releases/tag/v3.4.1), where the version update actually happened.

**Comment by RandomByte** [comment]
I looked into this and found it is the result of a conflict during the UI5 CLI v3.4.1 release.

## First v3.4.1 Release

The release job for v3.4.1 was started Aug 21, 2023, **9:13:41 AM** (UTC+2). The job starts by fetching the latest ui5-cli `main` branch.

During **the same minute** , https://github.com/SAP/ui5-cli/pull/646#pullrequestreview-1586343126 was submitted to be merged into `main` on the GitHub UI. GitHub merged to commit at **09:14:01** AM (`git show --no-patch --format=%ci b4d26f901671774236fff08b86ba5b841196a7ce`)

The job fails at **9:14:44 AM**, during the [`prepublishOnly`](https://docs.npmjs.com/cli/v10/using-npm/scripts#life-cycle-scripts) phase of `npm publish`, attempting to push the release commit (created and tagged by `npm version`) to GitHub:
```
> @ui5/cli@3.4.1 prepublishOnly
> git push --follow-tags

To https://github.com/SAP/ui5-cli
 * [new tag]         v3.4.1 -> v3.4.1
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'https://github.com/SAP/ui5-cli'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
```

The log shows that Git could not update the `main` branch, as it contained commits the local repository was missing. That's most likely https://github.com/SAP/ui5-cli/commit/b4d26f901671774236fff08b86ba5b841196a7ce of the aforementioned PR.

**However**, Git did manage to push the v3.4.1 tag and the associated release commit. This commit is still referenced in the [v3.4.1](https://github.com/SAP/ui5-cli/releases/tag/v3.4.1) GitHub release, which was created before the npm publishing started. On the GitHub UI, you can see that the commit does not belong to any branch: https://github.com/SAP/ui5-cli/commit/e0b39d2cdf420255bd261ccef6eff17cb9ce5bec

At this point, the ui5-cli v3.4.1 release was **not** published to the npm registry, it was **not** visible on the main branch but it was visible in the GitHub "release" view of the repository.

## Second v3.4.1 Release

At **9:16:52 AM** a second release job for ui5-cli was started. Likely because the first one failed and no release was showing up on npm.

The job repeated all the steps of the first released and ended up successfully pushing the release commit to the `main` branch: https://github.com/SAP/ui5-cli/commit/f10002df3115a03e9fbc067213d5fe9ca8e9ff1a. However, this commit was not tagged as v3.4.1, since the tag already existed.

## Release of v3.5.0

The next day a release job for ui5-cli v3.5.0 was started. Due to the lack of a Git tag on the `main` branch, the v3.4.1 release was invisible to the changelog generator (`git-chglog`). The relevant changes were therefore listed in the v3.5.0 release and its [release notes](https://github.com/SAP/ui5-cli/releases/tag/v3.5.0).

As you can see in the current [CHANGELOG.md](https://github.com/SAP/ui5-cli/blob/9c1eec6fa3336bd1d13dc1def4950b214599a686/CHANGELOG.md#v350---2023-08-22), the v3.4.1 release is still missing entirely.

# Findings

* During the second v3.4.1 release, `npm version` created a new release commit and tagged it as `v3.4.1`. However, `git push --follow-tags` did not push the tag to GitHub, but also did not raise an error. Ultimately this caused the incorrect changelog generation
* The changelog generation works as expected as it operates on the `main` branch only, which was missing the release tag
* It should be prevented to merge PRs while release jobs are running

# Immediate Actions

Even though this is not a critical issue, I executed the following actions to mitigate the impact of this incident:
1. Delete the old tag on GitHub: `git push origin :refs/tags/v3.4.1`
2. Create a new tag for https://github.com/SAP/ui5-cli/commit/f10002df3115a03e9fbc067213d5fe9ca8e9ff1a and push it using `git push --follow-tags`
3. Recreate the [v3.4.1 GitHub release](https://github.com/SAP/ui5-cli/releases/tag/v3.4.1)
4. Remove the incorrectly listed changes in [v3.5.0 release notes](https://github.com/SAP/ui5-cli/releases/tag/v3.5.0)

CHANGELOG.md will heal itself with the next release, since the v3.4.1 release is now visible to the changelog generator.

**Comment by RandomByte** [comment]
> * During the second v3.4.1 release, `npm version` created a new release commit and tagged it as `v3.4.1`. However, `git push --follow-tags` did not push the tag to GitHub, but also did not raise an error. Ultimately this caused the incorrect changelog generation

I enhanced the script to ensure the release tag is not yet present in the remote repository.

> * It should be prevented to merge PRs while release jobs are running

Unfortunately I couldn't find an API to easily lock the main branches during a release. There's an endpoint for [updating the branch protection rules](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#update-branch-protection), which would allow to set the `lock_branch` property. However, the request **must** also define the other settings like `required_status_checks`, which we actually don't want to change.

We do already change the `enforce_admins` property during a release. But luckily GitHub provides a [separate endpoint](https://docs.github.com/en/rest/branches/branch-protection?apiVersion=2022-11-28#set-admin-branch-protection) for that, which we use.

For locking the branches, we would probably have to fetch the current branch protection rules, update only the lock property and send that back. That's quite some implementation effort in the current release script, so let's maybe leave it at that for now and see how often this causes trouble.
